### ISSUE TITLE
Verify not working well with arrays as parameter

### ISSUE THREAD

**Issue by ivarvh** [NagRock/ts-mockito#26] opened 2017-06-13 07:38 UTC
Hey,

I noticed when I do a verify on a function that takes an array, for instance:

`verify(router.navigate(['/login'])).called();`

It tells me 

`Error: Expected "navigate(strictEqual(/login))" to be called at least 1 time(s).`

If I capture the arguments and then do an expect, it does work. Somehow it removed the array around it...

**Comment by NagRock** [comment] 2017-06-13 08:50
Thanks for reporting, I will take a look at this.

**Comment by ivarvh** [comment] 2017-06-13 09:21
2.0.0

**Comment by NagRock** [comment] 2017-06-14 12:51
I've added more precise information in 2.0.1
You will see now: `Error: Expected "navigate(strictEqual([/login]))" to be called at least 1 time(s).`
Array elements will be surrounded with `[ ]` square brackets.

But I think that on your case the problem is that you use `strictEqual` insted of `deepEqual`.

`strictEqual` check if two arrays are same instance. `deepEqual` checks array elements. So `verify(router.navigate(deepEqual(['/login']))).called();` should work on your case.

Please give me feedback if this fix your issue.

**Comment by ivarvh** [comment] 2017-06-15 05:31
Alright, in hindsight that makes a lot of sense, It would be cool to have some sort of a deepVerify function that automatically uses deepEqual for all parameters, because sometimes there are a lot of parameters and it sort of lessens the readability for me when you have to wrap all the params in deepEquals. But anyway thanks for the help!

**Comment by NagRock** [comment] 2017-06-15 17:40
I will think about deepVerify but now closing issue as deepEqual resolved your case.

**Closed by NagRock** 2017-06-15 17:40 UTC
